### ISSUE TITLE
Incorrect prefixing of "border" in transition

### ISSUE THREAD

**Issue by rtsao** [rofrischmann/inline-style-prefix-all#15]
```js
const prefix = require("inline-style-prefix-all");
prefix({transition: 'border 500ms linear'});

// result:
{
  transition: 'b-ms-order 500ms linear,b-webkit-order 500ms linear,border 500ms linear',
  WebkitTransition: 'b-webkit-order 500ms linear,border 500ms linear'
}
```

Runnable example: https://tonicdev.com/56aded3ffbbc390d004574ec/574f3d7550356a140044c255

Not quite sure what's going on yet. Same thing with `border-color`, etc. I think this has to do with the fact `order` is a substring of `border`.

**Comment by rofrischmann** [comment]
Oh my.. That's a nice bug actually. You're right! That's odd. Maybe we should just remove the `order` from transitions checklist as it can't be animated anyway. That might be the most simple way.

**Comment by rofrischmann** [comment]
Fixed this with https://github.com/rofrischmann/inline-style-prefixer/commit/b50fe1c6ddd20a6a69a468619c6d4fe8415ed546. I will deprecate the separate package in favor of `inline-style-prefixer/static` which is just much easier to maintain as its only one repo. Check back later today for a 2.0.0 of inline-style-prefixer
