### ISSUE TITLE
custom transition easing results in wrong output

### ISSUE THREAD

**Issue by Swatinem** [rofrischmann/inline-style-prefix-all#17]
This rule here:
```js
{
  transition: "transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000)"
}
```

results in the following broken output:

```js
{
  transition: "-ms-transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000),-webkit-transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000),transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000)",
  WebkitTransition: " 1.360, 0.680, 1.000),-webkit-transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000),transform 0.4s cubic-bezier(0.065, 1.360, 0.680, 1.000)"
}
```

**Comment by rofrischmann** [comment]
FYI: https://github.com/rofrischmann/inline-style-prefixer/commit/c1cb580e8c45735a46a84ac97c403866589d72be fixed this issue. I will deprecate the separate prefix-all package in favor of `inline-style-prefixer/static` to simplify maintaining both prefixer. It will get available with v2.0.0 today :)
