### ISSUE TITLE
Prefixes should come after unprefixed styles

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefix-all#3]
I noticed the vendor-prefixed CSS comes after the unprefixed CSS; it would be better to have the unprefixed CSS last.

From:

`display:flex; display:-webkit-flex`
`align-items: center; -webkit-align-items: center`

To:

`display:-webkit-flex; display:flex`
`-webkit-align-items:center; align-items: center`

**Comment by rofrischmann** [comment]
Are you sure this one happens because of the prefixer? I can't reproduce that one :/ Because e.g. https://github.com/rofrischmann/inline-style-prefix-all/blob/master/test/prefixAll-test.js#L133 shows exactly what you expect and all tests pass.

**Comment by necolas** [comment]
Might be my fault. I'll look a bit harder.
