### ISSUE TITLE
`alignSelf` inserts wrong value for `flex-start` and `flex-end`

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefix-all#4]
I've noticed `alignSelf` gets incorrect values:

`alignSelf: 'flex-start` -> `alignSelf: 'start'`
`alignSelf: 'flex-end` -> `alignSelf: 'end'`

The values should be `flex-start` and `flex-end`. I didn't look into other cases that might be wrong.

**Comment by rofrischmann** [comment]
@necolas Did the 1.0.3 release today :)

**Comment by necolas** [comment]
Thanks, much appreciated
